services:
  mongodb_projetDE:
    image: mongo
    container_name: mongodb_projetDE
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  webscraping_dashboard:
    build: .
    container_name: webscraping_dashboard
    ports:
      - "8050:8050"
    depends_on:
      - mongodb_projetDE
    environment:
      - MONGO_URI=mongodb://mongodb_projetDE:27017/projetDE
    restart: always
    volumes:
      - ./books.csv:/app/books.csv  # Partage le CSV entre le scraper et le dashboard

volumes:
  mongo_data:



  



